# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gilbert Anderson
name: Gilbert Anderson
email: gilbertandersonwork@gmail.com
description: Software Engineer & UX Designer

display_footer: inital  # change this to 'none' if you want to hide the footer copyright text

theme: jekyll-theme-merlot

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

# Settings for the porfolio section

portfolio_heading: Portfolio
portfolio_type: carousel # cards or carousel

project_one: UX Designs
project_one_description: UI dashboard design for Web App
project_one_url: https://drive.google.com/drive/folders/1MnmX9snQavMeDixlCBSKPtAXgSdJKyxu?usp=sharing
project_button: Google Drive
project_one_icon: typewriter # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

project_two: Dive Log
project_two_description: Capstone Project - Asset tracker
project_two_url: https://github.com/gilbertanderson/WOS_Dive_Log
project_button: Github
project_two_icon: typewriter

project_three: ReactJS Test App
project_three_description: App to show off features of ReactJS
project_three_url: https://github.com/gilbertanderson/React-Test-App
project_button: Github
project_three_icon: laptop_red

project_four: AngularJS Sample App
project_four_description: An app that allows users to like and dislike books while also filtering through a list built using AngularJS.
project_four_url: https://github.com/gilbertanderson/sample-angular-app
project_button: Github
project_four_icon: laptop_red

# Skill icons from https://konpa.github.io/devicon/
skills:
  - name: amazonwebservices
  - name: android
  - name: angularjs
  - name: apple
  - name: atom
  - name: bitbucket
  - name: bootstrap
  - name: chrome
  - name: confluence
  - name: cplusplus
  - name: csharp
  - name: css3
  - name: cucumber
  - name: d3js
  - name: docker
  - name: drupal
  - name: firefox
  - name: git
  - name: github
  - name: gitlab
  - name: google
  - name: html5
  - name: illustrator
  - name: itellij
  - name: java
  - name: javascript
  - name: less
  - name: linux
  - name: mongodb
  - name: mysql
  - name: nodejs
  - name: oracle
  - name: photoshop
  - name: protractor
  - name: postgresql
  - name: python
  - name: react
  - name: redhat
  - name: sass
  - name: slack
  - name: ssh
  - name: swift
  - name: typescript
  - name: ubuntu
  - name: vim
  - name: visualstudio
  - name: vuejs
  - name: webpack
  - name: webstorm
  - name: windows
  - name: wordpress

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/gilbertanderson/gilbertanderson.github.io
medium: https://medium.com

baseurl: / # if your site is located at /blog or /home, enter it here, otherwise leave it as '/'
url: https://gilbertanderson.github.io # the url of your site
medium: https://medium.com/@gilbertanderson
github:  https://github.com/gilbertanderson

google_analytics_tracking_id: UA-130517979-1 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

syntax_highlighting: true # include the css for syntax highlighting


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sass-converter
  - jekyll-minifier
