# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gilbert Anderson
name: Gilbert Anderson
email: gilbertandersonwork@gmail.com
description: Software Engineer

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: Jekyll Material Theme
project_one_description: A Jekyll Gem Theme based on Material Design using Materialize, currently being used on this site.
project_one_url: https://github.com/jameshamann/jekyll-material-theme
project_one_icon: web

project_two: Temp
project_two_description: Temp
project_two_url: https://github.com/gilbertanderson/temp
project_two_icon: local_movies

project_three: Temp
project_three_description: Temp
project_three_url: https://github.com/gilbertanderson/temp
project_three_icon: location_on

project_four: Pict
project_four_description: A library app that allows users to like and dislike books while also filtering through a list of books. Built using AngularJS.
project_four_url: https://github.com/gilbertanderson/sample-angular-app
project_button: Github
project_four_icon: photo_camera


github: https://github.com/gilbertanderson/gilbertanderson.github.io
medium: https://medium.com



baseurl: / # if your site is located at /blog or /home, enter it here, otherwise leave it as '/'
url: https://gilbertanderson.github.io # the url of your site
medium: https://medium.com/@gilbertanderson
github:  https://github.com/gilbertanderson

google_analytics_tracking_id: UA-temp # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!



# Build settings
markdown: kramdown

permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sass-converter
  - jekyll-minifier
